import { Metadata } from 'next';

import { DashboardLayout } from '@/components/DashboardLayout';
import { DashboardRouters } from '@/data/dashboard_routers';
import { BreadcrumbProps } from '@/interfaces';
import DashFunding from '@/components/DashFunding';

export const metadata: Metadata = {
  title: `MyStartup AI | Funding`,
  description: "Generated by create next app",
};

export default function Funding() {
  const breadcrumbs: BreadcrumbProps = [
    {
      title: 'Funding',
      href: DashboardRouters.funding
    }
  ]
  return (
    <>
      <DashboardLayout 
        header_title="Investors List"
        breadcrumbs={breadcrumbs}
        header_subtitle={`Here's your latest investors list`}
      >
        <DashFunding />      
      </DashboardLayout>
    </>
  );
}
