import { Metadata } from 'next';

export const metadata: Metadata = {
  title: `MyStartup AI | Legal`,
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <section>{children}</section>
}