import { Metadata } from 'next';
import { DashboardLayout } from '@/components/DashboardLayout';
import { DashboardRouters } from '@/data/dashboard_routers';
import { BreadcrumbProps } from '@/interfaces';
import ComingSoon from '@/components/ComingSoon';

export const metadata: Metadata = {
  title: `MyStartup AI | Document`,
  description: "Generated by create next app",
};

export default function Document() {
  const breadcrumbs: BreadcrumbProps = [
    {
      title: 'Documentations',
      href: DashboardRouters.document
    }
  ]
  return (
    <div>
      <DashboardLayout 
        header_title="Documentations"
        breadcrumbs={breadcrumbs}
      >
        {/* <DashBusiness /> */}
        <ComingSoon />
      </DashboardLayout>
    </div>
  );
}
