import { Metadata } from "next";

import LoginSignup from "@/components/LoginSignup";

export const metadata: Metadata = {
  title: `Login to your account`,
  description: "Generated by create next app",
};

export default function LoginPage() {
  return (
    <>
      <LoginSignup type="login" />
    </>
  );
}
