import { Metadata } from 'next';
import { legal_slugs, DashboardRouters } from '@/data/dashboard_routers';
import GeneratePlan from '@/components/DashboardLayout/GeneratePlan';
import { getProperName } from '@/operations/common';
import { BreadcrumbProps } from '@/interfaces';

export const metadata: Metadata = {
  title: "Legal",
  description: "Generated by create next app",
};

async function getPageData(page_url: any) {

  return legal_slugs.filter(slug => slug.url == page_url).length > 0;
  // return page_url;
}

export default async function LegalSlug(
  { params: { slug }, 
    searchParams: { task } } : 
  { params: { slug: string }, 
    searchParams: { task: string } 
  }
) {
  const isPageExist = await getPageData(slug) && task;
  const breadcrumbs: BreadcrumbProps = [
    {
      title: 'Legal',
      href: DashboardRouters.legal,
    },
    {
      title: getProperName(slug, '-'),
      href: slug,
    },
  ];

  return (
    <>
      {isPageExist ? 
        <GeneratePlan
          task_title={getProperName(task, "-")} 
          breadcrumbs={breadcrumbs}
          plan_type={breadcrumbs[0].title.toLowerCase()}
          subplan_type={getProperName(slug, '-')}
        />
      : <></>}
    </>
  );
}
