import { Metadata } from 'next';
import Home from './home/page';

export const metadata: Metadata = {
  title: `MyStartup AI | Dashboard`,
  description: "Generated by create next app",
};

export default function App() {
  
  return (
    <>
      <Home />
    </>
  );
}
