import { Metadata } from 'next';
import { DashboardLayout } from '@/components/DashboardLayout';
import { DashboardRouters } from '@/data/dashboard_routers';
import { BreadcrumbProps } from '@/interfaces';
import ComingSoon from '@/components/ComingSoon';

export const metadata: Metadata = {
  title: `MyStartup AI | Roadmap`,
  description: "Generated by create next app",
};

export default function RoadMap() {
  const breadcrumbs: BreadcrumbProps = [
    {
      title: 'Road Map',
      href: DashboardRouters.roadmap
    }
  ]
  return (
    <DashboardLayout 
      header_title="Road Map"
      breadcrumbs={breadcrumbs}
    >
      {/* <DashBusiness /> */}
      <ComingSoon />
    </DashboardLayout>
  );
}
